/*
 * This source file was generated by the Gradle 'init' task
 */
package todo;
import todo.Service.TodoService;
import todo.Entity.Todo;
import java.util.Scanner;

public class App {
    

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        TodoService todoService = new TodoService();  //create an object of our service
        int choice;

        do{
            System.out.println("1. Add todo");
            System.out.println("2. Update Status");
            System.out.println("3. Update Details");
            System.out.println("4. Delete todo");
            System.out.println("5. View Todos");
            System.out.println("6. Exit");
            System.out.println("Enter the choice");
            choice = scanner.nextInt();
            scanner.nextLine();



            // if(choice == 6){
            // System.out.println("Thanks");
        
        // }
        switch (choice) {
            case 1:
                System.out.println("Enter the title of the todo");
                String title = scanner.nextLine();
                System.out.println("Enter the Description of the task");
                String description = scanner.nextLine();
                todoService.addTodo(new Todo(title,description));  // created a new todo object
                //anonymous object creation
                break;

            case 2:
                todoService.viewTodos();
                System.out.println("Enter the id of the todo to update its status");
                int id = scanner.nextInt();
                scanner.nextLine();
                if(todoService.idFound(id)){
                    todoService.statusUpdate(id);
                    todoService.viewTodos();

                }
                else{
                    System.out.println("id not found");
                }
                break;
            
            case 3:
                todoService.viewTodos();
                System.out.println("Enter the id of the todo to update its description");
                id = scanner.nextInt();
                scanner.nextLine();
                if(todoService.idFound(id)){

                    System.out.println("Enter the updated description");
                    String UpDescription = scanner.nextLine();
                    todoService.updateTodo(id,UpDescription);
                }
                else{
                    System.out.println("Id not found");
                }
                break;
            
            case 4:
                todoService.viewTodos();

                System.out.println("Enter the id of the todo to delete");
                id = scanner.nextInt();
                scanner.nextLine();
                if(todoService.idFound(id)){
                    todoService.deleteTodo(id);
                }
                else{
                    System.out.println("Id not found");
                }
                break;

            case 5:
                todoService.viewTodos();
                break;

            case 6:
            System.out.println("GoodBye");
            break;
        
            default:
            System.out.println("Please enter a valid choice from 1 to 6");
                break;
        }
        }
        while(choice!=6);
        



        scanner.close();
    }
}
